base_url = "https://salif.eu"
theme = "linkita"
author = "salif"
default_language = "en"
compile_sass = false
minify_html = false

#[languages.en]
title = "Salif's site"
description = "My name is Salif Mehmed and this is my personal website. See a list of my coding projects and social profiles and how to contact me"
generate_feeds = false
build_search_index = true

[languages.bg]
title = "Сайтът на Салиф"
description = "Казвам се Салиф Мехмед и това е моят личен уебсайт. Вижте списък на моите проекти, социални профили и как да се свържете с мен"
generate_feeds = false
build_search_index = false

[languages.eo]
title = "La retejo de Salif"
description = "Mi nomiĝas Salif Mehmed kaj ĉi tio estas mia persona retejo. Vidu liston de miaj kodaj projektoj kaj sociaj profiloj kaj kiel kontakti min"
generate_feeds = false
build_search_index = false

[languages.tr]
title = "Salif'in web sitesi"
description = "Benim adım Salif Mehmed ve bu benim kişisel web sitem. Projelerimi, sosyal profillerimi ve benimle nasıl iletişime geçebileceğinizi görün"
generate_feeds = false
build_search_index = false

[markdown]
highlight_code = false
render_emoji = false
external_links_target_blank = true
smart_punctuation = false

[extra]
math = false
mermaid = false
comment = false
relative_urls = true
page_info = [{ when="date" }, { when="reading_time" }]
page_info_on_paginator = []
header_buttons = ["home_button", "theme_button", "search_button", "translations_button"]
invert_page_navigation = false
disable_default_favicon = false
use_cdn = false

[extra.style]
# The custom background color
bg_color = "#ffffff"
# The custom background color in dark mode
bg_dark_color = "#161e27"
# Enable header blur
header_blur = false
# The custom header color, only available when `header_blur` is false
header_color = "#ffffff"
# The custom header color in dark mode, only available when `header_blur` is false
header_dark_color = "#161e27"

[extra.profiles.salif]
name = "Salif Mehmed"
bio = "Welcome to my personal website"
email = "mail@salif.eu"
url = "https://salif.eu"
social = [
	{ name = "bluesky", url = "https://bsky.app/profile/did:plc:eirne2vlczwdejeegserrfyr" },
	{ name = "github", url = "https://github.com/salif" },
	{ name = "codeberg", url = "https://codeberg.org/salif" },
	{ name = "element", url = "https://matrix.to/#/@salif:mozilla.org" },
]

[extra.profiles.salif.languages.bg]
name = "Салиф Мехмед"
bio = "Добре дошли в моя личен сайт"
url = "https://salif.eu/bg/"
avatar_alt = "Моят аватар: Линукс пингвинът те наблюдава... с блестящите си очи!"

[extra.profiles.salif.languages.eo]
name = "Salif Mehmed"
bio = "Bonvenon al mia persona retejo"
url = "https://salif.eu/eo/"
avatar_alt = "Mia avataro: La pingveno de Linukso rigardas vin... per siaj brilaj okuloj!"

[extra.profiles.salif.languages.tr]
name = "Salif Mehmed"
bio = "Web siteme hoş geldiniz"
url = "https://salif.eu/tr/"
avatar_alt = "Avatarım: Linux pengueni seni izliyor... parlayan gözleriyle!"

[extra.profiles.salif.open_graph]
first_name = "Salif"
last_name = "Mehmed"
username = "salif"
gender = "male"

[extra.profiles.salif.open_graph.fediverse_creator]
handle = "13"
domain = "sharkey.world"

[extra.languages.en]
locale = "en_US"
date_format = "%x"

[extra.languages.bg]
locale = "bg_BG"
date_format = "%x"

[extra.languages.eo]
locale = "eo"
date_format = "%x"

[extra.languages.tr]
locale = "tr_TR"
date_format = "%x"

[extra.footer]
since = 2024
