base_url = "https://salif.eu"
theme = "linkita"
author = "salif"
default_language = "en"
compile_sass = false
generate_feeds = false
build_search_index = true
minify_html = false

[languages.en]
title = "salif.eu"
description = "My personal website"

[languages.bg]
title = "salif.eu"
description = "Моят личен сайт"

[languages.eo]
title = "salif.eu"
description = "Mia persona retejo"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false
render_emoji = false
external_links_target_blank = true
smart_punctuation = false

[extra]
math = false
mermaid = false
comment = false
# header_menu_name = "main"
page_info = ["date_on_page", "date_updated_on_page", "reading_time_on_page", "authors_on_page"]
header_buttons = ["home_button", "theme_button", "search_button", "translations_button"]
disable_default_favicon = true
disable_javascript = false

[extra.style]
# The custom background color
bg_color = "#e6e9ef"
# The custom background color in dark mode
bg_dark_color = "#161e27"
# Enable header blur
header_blur = false
# The custom header color, only available when `header_blur` is false
header_color = "#e6e9ef"
# The custom header color in dark mode, only available when `header_blur` is false
header_dark_color = "#161e27"

[[extra.menus.main]]
url = "$BASE_URL/about/"
name = "About"
names = { bg = "За сайта", eo = "Pri la retejo" }

[[extra.menus.main]]
url = "https://bg.salif.eu"
name = "Blog"
names = { bg = "Моят блог", eo = "Mia blogo" }

[extra.profiles.salif]
avatar_url = "ico/android-icon-192x192.png"
avatar_alt = "My avatar: Tux is watching you... with his glowing eyes"
avatar_invert = false
name = "Salif Mehmed"
bio = "Welcome to my personal website"
email = "mail@salif.eu"
url = "https://salif.eu"
social = [
	{ name = "bluesky", url = "https://bsky.app/profile/did:plc:3ebgy675tgwzqudufqvifpxv" },
	{ name = "github", url = "https://github.com/salif" },
	{ name = "codeberg", url = "https://codeberg.org/salif" },
]

[extra.profiles.salif.languages.bg]
name = "Салиф Мехмед"
bio = "Добре дошли в моя личен сайт"
url = "https://salif.eu/bg/"
avatar_alt = "Моят аватар: Линукс пингвинът те наблюдава... с блестящите си очи!"

[extra.profiles.salif.languages.eo]
name = "Salif Mehmed"
bio = "Bonvenon al mia persona retejo"
url = "https://salif.eu/eo/"
avatar_alt = "Mia avataro: La pingveno de Linukso rigardas vin... per siaj brilaj okuloj!"

[extra.profiles.salif.open_graph]
first_name = "Salif"
last_name = "Mehmed"
username = "salif"
gender = "male"

[extra.profiles.salif.open_graph.fediverse_creator]
handle = "bg.salif.eu"
domain = "bsky.brid.gy"
url = "https://bsky.brid.gy/r/https://bsky.app/profile/bg.salif.eu"

[extra.languages.en]
locale = "en_US"
date_format = "%x"
date_format_archive = "%m-%d"

[extra.languages.bg]
locale = "bg_BG"
date_format = "%x"
date_format_archive = "%d.%m"

[extra.languages.eo]
locale = "eo"
date_format = "%x"
date_format_archive = "%d.%m"

[extra.footer]
since = 2024

[extra.vercel_analytics]
src = "/_vercel/insights/script.js"
