[[project]]
name = ""
desc = """
|  |  |
| --- | --- |
| GitHub | [github.com/salif](https://github.com/salif) |
| Codeberg | [codeberg.org/salif](https://codeberg.org/salif) |
"""
tags = []
links = []


[[project]]
name = ""
desc = """
|  |  |
| --- | --- |
| Hex | [hex.pm/users/lumalee](https://hex.pm/users/lumalee) |
| AUR | [aur.archlinux.org/account/salif](https://aur.archlinux.org/account/salif) |
| npm | [npmjs.com/~salifm](https://www.npmjs.com/~salifm) |
| Launchpad | [launchpad.net/~salifm](https://launchpad.net/~salifm) |
| Docker | [hub.docker.com/u/salifm](https://hub.docker.com/u/salifm) |
| Ballerina Central | [central.ballerina.io/ballet](https://central.ballerina.io/ballet) |
"""
tags = []
links = []

[[project]]
name = ""
desc = """
|  |  |
| --- | --- |
| LinkedIn | [linkedin.com/in/salifm](https://www.linkedin.com/in/salifm) |
| Hashnode | [hashnode.com/@salif](https://hashnode.com/@salif) |
| Disqus | [disqus.com/by/salifm](https://disqus.com/by/salifm) |
| Bluesky | [bg.salif.eu](https://bsky.app/profile/did:plc:3ebgy675tgwzqudufqvifpxv) |
"""
tags = []
links = []

[[project]]
name = ""
desc = """
|  |  |
| --- | --- |
| Weblate | [hosted.weblate.org/user/13](https://hosted.weblate.org/user/13) |
| Weblate | [translate.codeberg.org/user/salif](https://translate.codeberg.org/user/salif) |
| Weblate | [weblate.join-lemmy.org/user/salif](https://weblate.join-lemmy.org/user/salif) |
| Weblate | [weblate.tusky.app/user/13](https://weblate.tusky.app/user/13) |
| Weblate | [translate.iceshrimp.dev/user/13](https://translate.iceshrimp.dev/user/13) |
| Weblate | [weblate.framasoft.org/user/salif](https://weblate.framasoft.org/user/salif) |
| Weblate | [weblate.xylight.dev/user/salif](https://weblate.xylight.dev/user/salif) |
| Crowdin | [crowdin.com/profile/salifm](https://crowdin.com/profile/salifm) |
"""
tags = []
links = []

[[project]]
name = ""
desc = """
|  |  |
| --- | --- |
| WakaTime | [wakatime.com/@salif](https://wakatime.com/@salif) |
| Exercism | [exercism.org/profiles/salif](https://exercism.org/profiles/salif)|
| HackerRank | [hackerrank.com/salif](https://www.hackerrank.com/salif) |
| Sololearn | [sololearn.com/profile/7499537](https://www.sololearn.com/profile/7499537) |
| W3Schools | [w3profile.com/13](https://www.w3profile.com/13) |
| 10FastFingers | [10fastfingers.com/user/1849490](https://10fastfingers.com/user/1849490) |
| YouTube | [youtube.com/@Jutubisto](https://www.youtube.com/@Jutubisto) |
| Keybase | [keybase.io/salifm_](https://keybase.io/salifm_) |
| daily.dev | [app.daily.dev/salifm](https://app.daily.dev/salifm) |
| Holopin | [holopin.io/@salif](https://www.holopin.io/@salif) |
"""
tags = []
links = []
