[[project]]
name = "morse-code-translator"
desc = "Morse Code Translator"
tags = ["Gleam"]
links = [
	{ name = "web page", url = "https://salif.github.io/morse-code-translator/" },
    { name = "on codeberg", url = "https://codeberg.org/salif/morse-code-translator" },
	{ name = "on github", url = "https://github.com/salif/morse-code-translator" },
]

[[project]]
name = "gu"
desc = "Zenity GUI dialogs Gleam wrapper"
tags = ["Gleam"]
links = [
	{ name = "on hex.pm", url = "https://hex.pm/packages/gu" },
    { name = "on codeberg", url = "https://codeberg.org/salif/gu" },
	{ name = "on github", url = "https://github.com/salif/gu" },
]

[[project]]
name = "nemo_gleam"
desc = "GUI extension for Gleam development"
tags = ["Gleam"]
links = [
	{ name = "on codeberg", url = "https://codeberg.org/salif/nemo_gleam" },
	{ name = "on github", url = "https://github.com/salif/nemo_gleam" },
]

[[project]]
name = "aham"
desc = "Build multilingual Gleam applications"
tags = ["Gleam"]
links = [
    { name = "on hex.pm", url = "https://hex.pm/packages/aham" },
    { name = "on codeberg", url = "https://codeberg.org/salif/aham" },
    { name = "on github", url = "https://github.com/salif/aham" },
]

[[project]]
name = "mon"
desc = "A library for building decks"
tags = ["Gleam"]
links = [
	{ name = "on codeberg", url = "https://codeberg.org/salif/mon" },
	{ name = "on github", url = "https://github.com/salif/mon" },
]

[[project]]
name = "gleam-open-color"
desc = "Gleam implementation of the Open Color scheme"
tags = ["Gleam"]
links = [
	{ name = "on hex.pm", url = "https://hex.pm/packages/open_color" },
	{ name = "on github", url = "https://github.com/salif/gleam-open-color" },
]

[[project]]
name = "sinhrz"
desc = "A simple folder synchronization tool"
tags = ["Java"]
links = [
	{ name = "web page", url = "https://salif.github.io/sinhrz/" },
    { name = "on github", url = "https://github.com/salif/sinhrz" },
    { name = "on codeberg", url = "https://codeberg.org/salif/sinhrz" },
]

[[project]]
name = "Tetris"
desc = "Fun and simple original tetris"
tags = ["Java"]
links = [
	{ name = "web page", url = "https://salif.github.io/Tetris/" },
    { name = "on github", url = "https://github.com/salif/Tetris" },
]

[[project]]
name = "gramati-fe-globasa"
desc = "Translations of the Complete Globasa Grammar"
tags = ["Language"]
links = [
    { name = "web page", url = "https://salif.github.io/gramati-fe-globasa/" },
    { name = "on codeberg", url = "https://codeberg.org/salif/gramati-fe-globasa" },
    { name = "on github", url = "https://github.com/salif/gramati-fe-globasa" },
]

[[project]]
name = "globasa-xwexi-pages"
desc = "Bulgarian translation of Globasa Lessons for Beginners"
tags = ["Language"]
links = [
	{ name = "web page", url = "https://salif.github.io/globasa-xwexi-pages/" },
    { name = "on github", url = "https://github.com/salif/globasa-xwexi-pages" },
    { name = "on codeberg", url = "https://codeberg.org/salif/globasa-xwexi-pages" },
]

[[project]]
name = "tok-bul-dict"
desc = "Toki Pona - Bulgarian dictionary"
tags = ["Language"]
links = [
	{ name = "web page", url = "https://salif.github.io/tok-bul-dict/" },
    { name = "on github", url = "https://github.com/salif/tok-bul-dict" },
    { name = "on codeberg", url = "https://codeberg.org/salif/tok-bul-dict" },
]

[[project]]
name = "gleam-tour-bg"
desc = "Научете Gleam във вашия браузър!"
tags = ["Language"]
links = [
	{ name = "on github", url = "https://github.com/salif/gleam-tour-bg" },
]

[[project]]
name = "alfabetoj"
desc = "Esperanto alphabet converter"
tags = ["Language"]
links = [
	{ name = "web page", url = "https://salif.github.io/alfabetoj/" },
    { name = "on github", url = "https://github.com/salif/alfabetoj" },
    { name = "on codeberg", url = "https://codeberg.org/salif/alfabetoj" },
]

[[project]]
name = "dotfiles"
desc = "My dotfiles"
tags = ["Linux"]
links = [
	{ name = "web page", url = "https://salif.github.io/dotfiles" },
    { name = "on codeberg", url = "https://codeberg.org/salif/dotfiles" },
    { name = "on github", url = "https://github.com/salif/dotfiles" },
]

[[project]]
name = "cli-games"
desc = "Games in the terminal"
tags = ["Linux"]
links = [
	{ name = "web page", url = "https://salif.github.io/cli-games/" },
	{ name = "on github", url = "https://github.com/salif/cli-games" },
]

[[project]]
name = "lemmy-onion-service"
desc = "Self-hosted Lemmy using the Tor network"
tags = ["Linux"]
links = [
    { name = "on github", url = "https://github.com/salif/lemmy-onion-service" },
]

[[project]]
name = "colemak-eo"
desc = "Esperanto (Colemak) keyboard layout"
tags = ["KeyboardLayouts"]
links = [
	{ name = "web page", url = "https://salif.github.io/colemak-eo/" },
    { name = "on codeberg", url = "https://codeberg.org/salif/colemak-eo" },
    { name = "on github", url = "https://github.com/salif/colemak-eo" },
]

[[project]]
name = "colemak-bg"
desc = "Bulgarian (Colemak) keyboard layout"
tags = ["KeyboardLayouts"]
links = [
	{ name = "web page", url = "https://salif.github.io/colemak-bg/" },
    { name = "on codeberg", url = "https://codeberg.org/salif/colemak-bg" },
    { name = "on github", url = "https://github.com/salif/colemak-bg" },
]

[[project]]
name = "colemak-tr"
desc = "Turkish (Colemak) keyboard layout"
tags = ["KeyboardLayouts"]
links = [
	{ name = "web page", url = "https://salif.github.io/colemak-tr/" },
    { name = "on codeberg", url = "https://codeberg.org/salif/colemak-tr" },
    { name = "on github", url = "https://github.com/salif/colemak-tr" },
]

[[project]]
name = "shaw-eo"
desc = "Esperanto (Shavian) keyboard layout"
tags = ["KeyboardLayouts"]
links = [
	{ name = "web page", url = "https://salif.github.io/shaw-eo/" },
    { name = "on codeberg", url = "https://codeberg.org/salif/shaw-eo" },
    { name = "on github", url = "https://github.com/salif/shaw-eo" },
]

[[project]]
name = "QA"
desc = "Question and answer (Q&A) site"
tags = ["Inactive"]
links = [
	{ name = "web page", url = "https://salif.github.io/QA/" },
    { name = "on github", url = "https://github.com/salif/QA" },
    { name = "on codeberg", url = "https://codeberg.org/salif/QA" },
]

[[project]]
name = "hasher"
desc = "Library and cli tool for password hashing"
tags = ["Inactive"]
links = [
	{ name = "web page", url = "https://salif.github.io/hasher/" },
    { name = "on github", url = "https://github.com/salif/hasher" },
    { name = "on codeberg", url = "https://codeberg.org/salif/hasher" },
]

[[project]]
name = "komiki-mono"
desc = "Comic Mono with ligatures"
tags = ["Inactive"]
links = [
	{ name = "on github", url = "https://github.com/salif/komiki-mono" },
]

[[project]]
name = "mbin-custom-css"
desc = "Mbin/Kbin Custom CSS Themes"
tags = ["Inactive"]
links = [
	{ name = "on github", url = "https://github.com/salif/mbin-custom-css" },
]

[[project]]
name = "hide-text"
desc = "Hide a secret text message inside a text message"
tags = ["Inactive"]
links = [
	{ name = "on npmjs", url = "https://www.npmjs.com/package/@salifm/hide-text" },
	{ name = "on codeberg", url = "https://codeberg.org/salif/hide-text" },
	{ name = "on github", url = "https://github.com/salif/hide-text" },
]

[[project]]
name = "chat"
desc = "PHP/SQLite chat design"
tags = ["Inactive"]
links = [
	{ name = "on github", url = "https://github.com/salif/chat" },
	{ name = "on codeberg", url = "https://codeberg.org/salif/chat" },
]

[[project]]
name = "ballerina-rosettacode"
desc = "Tasks from Rosetta Code implemented in Ballerina"
tags = ["Inactive"]
links = [
	{ name = "on github", url = "https://github.com/salif/ballerina-rosettacode" },
	{ name = "on codeberg", url = "https://codeberg.org/salif/ballerina-rosettacode" },
]

[[project]]
name = "projstats"
desc = "Count source lines of code"
tags = ["Archived"]
links = [
	{ name = "on github", url = "https://github.com/salif/projstats" },
]

[[project]]
name = "TypingTest"
desc = ""
tags = ["Archived"]
links = [
	{ name = "on github", url = "https://github.com/salif/TypingTest" },
]

[[project]]
name = "pdftros"
desc = ""
tags = ["Archived"]
links = [
	{ name = "on github", url = "https://github.com/salif/pdftros" },
]

[[project]]
name = "maze"
desc = ""
tags = ["Archived"]
links = [
	{ name = "web page", url = "https://salif.github.io/maze/" },
	{ name = "on github", url = "https://github.com/salif/maze" },
]

[[project]]
name = "colemak-ru"
desc = "Russian (Colemak) keyboard layout"
tags = ["Archived"]
links = [
	{ name = "web page", url = "https://salif.github.io/colemak-ru/" },
	{ name = "on codeberg", url = "https://codeberg.org/salif/colemak-ru" },
	{ name = "on github", url = "https://github.com/salif/colemak-ru" },
]

[[project]]
name = "esiromem"
desc = "For memorizing things, using spaced repetition"
tags = ["Concept"]
links = [
	{ name = "on github", url = "https://github.com/salif/esiromem" },
]

[[project]]
name = "glance_printer_bal"
desc = "Turn glance AST into a Ballerina source code"
tags = ["Concept"]
links = [
	{ name = "on codeberg", url = "https://codeberg.org/salif/glance_printer_bal" },
	{ name = "on github", url = "https://github.com/salif/glance_printer_bal" },
]

[[project]]
name = "pvcure"
desc = "Cipher"
tags = ["Concept"]
links = [
	{ name = "web page", url = "https://salif.github.io/pvcure/" },
	{ name = "on github", url = "https://github.com/salif/pvcure" },
]
