[[project]]
name = "Linkita"
desc = "A clean and elegant blog theme for Zola"
tags = ["Zola"]
links = [
	{ name = "web page", url = "https://salif.github.io/linkita/" },
	{ name = "on codeberg", url = "https://codeberg.org/salif/linkita" },
	{ name = "on github", url = "https://github.com/salif/linkita" },
]
[project.languages.bg]
tags = ["Зола"]
desc = "Изчистена и елегантна блог тема за Зола"

[[project]]
name = "Zola Themes Collection"
desc = "A curated directory of themes for Zola"
tags = ["Zola"]
links = [
	{ name = "web page", url = "https://salif.github.io/zola-themes-collection/" },
	{ name = "on github", url = "https://github.com/salif/zola-themes-collection" },
]
[project.languages.bg]
tags = ["Зола"]
desc = "Директория с подбрани теми за Зола"

[[project]]
name = "Tukan"
desc = "A Zola theme inspired from Toucan"
tags = ["Zola"]
links = [
	{ name = "web page", url = "https://salif.github.io/zola-themes-collection/demo/tukan/" },
	{ name = "on codeberg", url = "https://codeberg.org/salif/tukan" },
	{ name = "on github", url = "https://github.com/salif/tukan" },
]
[project.languages.bg]
tags = ["Зола"]
desc = "Блог тема за Зола, вдъхновена от Toucan"

[[project]]
name = "Gramati fe Globasa"
desc = "Translations of the Complete Globasa Grammar"
tags = ["Language"]
links = [
    { name = "web page", url = "https://salif.github.io/gramati-fe-globasa/" },
    { name = "on codeberg", url = "https://codeberg.org/salif/gramati-fe-globasa" },
    { name = "on github", url = "https://github.com/salif/gramati-fe-globasa" },
]
[project.languages.bg]
tags = ["Език"]
desc = "Преводи на пълната граматика на глобаса"

[[project]]
name = "Globasa-Xwexi"
desc = "Bulgarian translation of Globasa Lessons for Beginners"
tags = ["Language"]
links = [
	{ name = "web page", url = "https://salif.github.io/globasa-xwexi-pages/" },
    { name = "on github", url = "https://github.com/salif/globasa-xwexi-pages" },
]
[project.languages.bg]
tags = ["Език"]
desc = "Български превод на уроците по глобаса за начинаещи"

[[project]]
name = "Globasa-Jaribas"
desc = "Experimental Globasa translator"
tags = ["Language"]
links = [
	{ name = "web page", url = "https://salif.github.io/globasa-jaribas/" },
	{ name = "on codeberg", url = "https://codeberg.org/salif/globasa-jaribas" },
	{ name = "on github", url = "https://github.com/salif/globasa-jaribas" },
]
[project.languages.bg]
tags = ["Език"]
desc = "Експериментален преводач за глобаса"

[[project]]
name = "globasa-rechnik"
desc = "Unofficial Globasa - Bulgarian dictionary"
tags = ["Language"]
links = [
	{ name = "on codeberg", url = "https://codeberg.org/salif/globasa-rechnik" },
	{ name = "web page", url = "https://salif.github.io/globasa-xwexi-pages/05.max-resurso.dict.default.bul.html" },
]
[project.languages.bg]
tags = ["Език"]
desc = "Неофициален глобаса - български речник"

[[project]]
name = "alfabetoj"
desc = "Esperanto alphabet converter"
tags = ["Language"]
links = [
	{ name = "web page", url = "https://salif.github.io/alfabetoj/" },
    { name = "on github", url = "https://github.com/salif/alfabetoj" },
    { name = "on codeberg", url = "https://codeberg.org/salif/alfabetoj" },
]
[project.languages.bg]
tags = ["Език"]
desc = "Конвертор между азбуки за есперанто"

[[project]]
name = "Morse Code Translator"
desc = "Morse Code Translator written in Gleam"
tags = ["Gleam"]
links = [
	{ name = "web page", url = "https://salif.github.io/morse-code-translator/" },
    { name = "on codeberg", url = "https://codeberg.org/salif/morse-code-translator" },
	{ name = "on github", url = "https://github.com/salif/morse-code-translator" },
]
[project.languages.bg]
desc = "Преводач на морзов код"

[[project]]
name = "gu"
desc = "Zenity GUI dialogs Gleam wrapper"
tags = ["Gleam"]
links = [
	{ name = "on hex.pm", url = "https://hex.pm/packages/gu" },
    { name = "on codeberg", url = "https://codeberg.org/salif/gu" },
	{ name = "on github", url = "https://github.com/salif/gu" },
]
[project.languages.bg]
desc = "Zenity GUI dialogs Gleam wrapper"

[[project]]
name = "nemo_gleam"
desc = "Graphical user interface for Gleam development"
tags = ["Gleam"]
links = [
	{ name = "on codeberg", url = "https://codeberg.org/salif/nemo_gleam" },
	{ name = "on github", url = "https://github.com/salif/nemo_gleam" },
]
[project.languages.bg]
desc = "Графичен интерфейс за управление и разработка за Gleam"

[[project]]
name = "aham"
desc = "Build multilingual Gleam applications"
tags = ["Gleam"]
links = [
    { name = "on hex.pm", url = "https://hex.pm/packages/aham" },
    { name = "on codeberg", url = "https://codeberg.org/salif/aham" },
    { name = "on github", url = "https://github.com/salif/aham" },
]
[project.languages.bg]
desc = "За създаване на многоезични приложения с Gleam"

[[project]]
name = "mon"
desc = "A library for building decks"
tags = ["Gleam"]
links = [
	{ name = "on codeberg", url = "https://codeberg.org/salif/mon" },
	{ name = "on github", url = "https://github.com/salif/mon" },
]
[project.languages.bg]
desc = "Библиотека за създаване на тестета"

[[project]]
name = "gleam-open-color"
desc = "Gleam implementation of the Open Color scheme"
tags = ["Gleam"]
links = [
	{ name = "on hex.pm", url = "https://hex.pm/packages/open_color" },
	{ name = "on github", url = "https://github.com/salif/gleam-open-color" },
]
[project.languages.bg]
desc = "Gleam implementation of the Open Color scheme"

[[project]]
name = "sinhrz"
desc = "A simple folder synchronization tool"
tags = ["Java"]
links = [
    { name = "on github", url = "https://github.com/salif/sinhrz" },
    { name = "on codeberg", url = "https://codeberg.org/salif/sinhrz" },
]
[project.languages.bg]
tags = ["Джава"]
desc = "Прост инструмент за синхронизация на папки"

[[project]]
name = "Tetris"
desc = "Fun and simple original tetris"
tags = ["Java"]
links = [
	{ name = "web page", url = "https://salif.github.io/Tetris/" },
    { name = "on github", url = "https://github.com/salif/Tetris" },
]
[project.languages.bg]
tags = ["Джава"]
desc = "Забавен и прост оригинален тетрис"

[[project]]
name = "dotfiles"
desc = "My dotfiles"
tags = ["Linux"]
links = [
	{ name = "web page", url = "https://salif.github.io/dotfiles" },
    { name = "on codeberg", url = "https://codeberg.org/salif/dotfiles" },
    { name = "on github", url = "https://github.com/salif/dotfiles" },
]
[project.languages.bg]
tags = ["Линукс"]
desc = "Моите dotfiles"

[[project]]
name = "lemmy-onion-service"
desc = "Self-hosted Lemmy using the Tor network"
tags = ["Linux"]
links = [
    { name = "on github", url = "https://github.com/salif/lemmy-onion-service" },
]
[project.languages.bg]
tags = ["Линукс"]
desc = "Self-hosted Lemmy using the Tor network"

[[project]]
name = "colemak-eo"
desc = "Esperanto (Colemak) keyboard layout"
tags = ["Keyboard Layouts"]
links = [
	{ name = "web page", url = "https://salif.github.io/colemak-eo/" },
    { name = "on codeberg", url = "https://codeberg.org/salif/colemak-eo" },
    { name = "on github", url = "https://github.com/salif/colemak-eo" },
]
[project.languages.bg]
tags = ["Клавиатурни подредби"]
desc = "Клавиатурна подредба за есперанто (Colemak)"

[[project]]
name = "colemak-bg"
desc = "Bulgarian (Colemak) keyboard layout"
tags = ["Keyboard Layouts"]
links = [
	{ name = "web page", url = "https://salif.github.io/colemak-bg/" },
    { name = "on codeberg", url = "https://codeberg.org/salif/colemak-bg" },
    { name = "on github", url = "https://github.com/salif/colemak-bg" },
]
[project.languages.bg]
tags = ["Клавиатурни подредби"]
desc = "Клавиатурна подредба за български (Colemak)"

[[project]]
name = "colemak-tr"
desc = "Turkish (Colemak) keyboard layout"
tags = ["Keyboard Layouts"]
links = [
	{ name = "web page", url = "https://salif.github.io/colemak-tr/" },
    { name = "on codeberg", url = "https://codeberg.org/salif/colemak-tr" },
    { name = "on github", url = "https://github.com/salif/colemak-tr" },
]
[project.languages.bg]
tags = ["Клавиатурни подредби"]
desc = "Клавиатурна подредба за турски (Colemak)"

[[project]]
name = "shaw-eo"
desc = "Esperanto (Shavian) keyboard layout"
tags = ["Keyboard Layouts"]
links = [
	{ name = "web page", url = "https://salif.github.io/shaw-eo/" },
    { name = "on codeberg", url = "https://codeberg.org/salif/shaw-eo" },
    { name = "on github", url = "https://github.com/salif/shaw-eo" },
]
[project.languages.bg]
tags = ["Клавиатурни подредби"]
desc = "Шавианска клавиатурна подредба за есперанто"

[[project]]
name = "tok-bul-dict"
desc = "Toki Pona - Bulgarian dictionary"
tags = ["Inactive"]
links = [
	{ name = "web page", url = "https://salif.github.io/tok-bul-dict/" },
    { name = "on github", url = "https://github.com/salif/tok-bul-dict" },
    { name = "on codeberg", url = "https://codeberg.org/salif/tok-bul-dict" },
]
[project.languages.bg]
tags = ["Неактивни"]
desc = "Неофициален токи пона - български речник"

[[project]]
name = "gleam-tour-bg"
desc = "Научете Gleam във вашия браузър!"
tags = ["Inactive"]
links = [
	{ name = "on github", url = "https://github.com/salif/gleam-tour-bg" },
]
[project.languages.bg]
tags = ["Неактивни"]
desc = "Научете Gleam във вашия браузър!"

[[project]]
name = "QA"
desc = "Question and answer (Q&A) site"
tags = ["Inactive"]
links = [
    { name = "on github", url = "https://github.com/salif/QA" },
    { name = "on codeberg", url = "https://codeberg.org/salif/QA" },
]
[project.languages.bg]
tags = ["Неактивни"]
desc = "Сайт за въпроси и отговори (Q&A)"

[[project]]
name = "hasher"
desc = "Library and cli tool for password hashing"
tags = ["Inactive"]
links = [
    { name = "on github", url = "https://github.com/salif/hasher" },
    { name = "on codeberg", url = "https://codeberg.org/salif/hasher" },
]
[project.languages.bg]
tags = ["Неактивни"]
desc = "Библиотека и инструмент за команден ред за хеширане на пароли"

[[project]]
name = "komiki-mono"
desc = "Comic Mono with ligatures"
tags = ["Inactive"]
links = [
	{ name = "on github", url = "https://github.com/salif/komiki-mono" },
]
[project.languages.bg]
tags = ["Неактивни"]
desc = "Шрифт Comic Mono с лигатури"

[[project]]
name = "mbin-custom-css"
desc = "Mbin Custom CSS Themes"
tags = ["Inactive"]
links = [
	{ name = "on github", url = "https://github.com/salif/mbin-custom-css" },
]
[project.languages.bg]
tags = ["Неактивни"]
desc = "Персонализирани CSS теми за Mbin"

[[project]]
name = "hide-text"
desc = "Hide a secret text message inside a text message"
tags = ["Inactive"]
links = [
	{ name = "on npmjs", url = "https://www.npmjs.com/package/@salifm/hide-text" },
	{ name = "on codeberg", url = "https://codeberg.org/salif/hide-text" },
	{ name = "on github", url = "https://github.com/salif/hide-text" },
]
[project.languages.bg]
tags = ["Неактивни"]
desc = "За скриване на текстово съобщение в друго текстово съобщение"

[[project]]
name = "chat"
desc = "PHP/SQLite chat design"
tags = ["Inactive"]
links = [
	{ name = "on github", url = "https://github.com/salif/chat" },
	{ name = "on codeberg", url = "https://codeberg.org/salif/chat" },
]
[project.languages.bg]
tags = ["Неактивни"]
desc = "Дизайн на чат с PHP/SQLite"

[[project]]
name = "ballerina-rosettacode"
desc = "Tasks from Rosetta Code implemented in Ballerina"
tags = ["Inactive"]
links = [
	{ name = "on github", url = "https://github.com/salif/ballerina-rosettacode" },
	{ name = "on codeberg", url = "https://codeberg.org/salif/ballerina-rosettacode" },
]
[project.languages.bg]
tags = ["Неактивни"]
desc = "Задачи от Rosetta Code, реализирани на Ballerina"

[[project]]
name = "projstats"
desc = "Count source lines of code"
tags = ["Archived"]
links = [
	{ name = "on github", url = "https://github.com/salif/projstats" },
]
[project.languages.bg]
tags = ["Архивирани"]
desc = "За преброяване на редовете на изходния код"

[[project]]
name = "TypingTest"
desc = ""
tags = ["Archived"]
links = [
	{ name = "on github", url = "https://github.com/salif/TypingTest" },
]
[project.languages.bg]
tags = ["Архивирани"]
desc = ""

[[project]]
name = "pdftros"
desc = ""
tags = ["Archived"]
links = [
	{ name = "on github", url = "https://github.com/salif/pdftros" },
]
[project.languages.bg]
tags = ["Архивирани"]
desc = ""

[[project]]
name = "maze"
desc = ""
tags = ["Archived"]
links = [
	{ name = "web page", url = "https://salif.github.io/maze/" },
	{ name = "on github", url = "https://github.com/salif/maze" },
]
[project.languages.bg]
tags = ["Архивирани"]
desc = ""

[[project]]
name = "colemak-ru"
desc = "Russian (Colemak) keyboard layout"
tags = ["Archived"]
links = [
	{ name = "on codeberg", url = "https://codeberg.org/salif/colemak-ru" },
	{ name = "on github", url = "https://github.com/salif/colemak-ru" },
]
[project.languages.bg]
tags = ["Архивирани"]
desc = "Клавиатурна подредба за руски (Colemak)"

[[project]]
name = "esiromem"
desc = "For memorizing things, using spaced repetition"
tags = ["Concept"]
links = [
	{ name = "on github", url = "https://github.com/salif/esiromem" },
]
[project.languages.bg]
tags = ["Концепция"]
desc = "За запаметяване на неща, използвайки метода на интервално повторение"

[[project]]
name = "glance_printer_bal"
desc = "Turn glance AST into a Ballerina source code"
tags = ["Concept"]
links = [
	{ name = "on codeberg", url = "https://codeberg.org/salif/glance_printer_bal" },
	{ name = "on github", url = "https://github.com/salif/glance_printer_bal" },
]
[project.languages.bg]
tags = ["Концепция"]
desc = "Превръщане на glance AST в изходен код на Ballerina"

[[project]]
name = "pvcure"
desc = "Cipher"
tags = ["Concept"]
links = [
	{ name = "web page", url = "https://salif.github.io/pvcure/" },
	{ name = "on github", url = "https://github.com/salif/pvcure" },
]
[project.languages.bg]
tags = ["Концепция"]
desc = "Шифър"
