[[project]]
name = "Forgejo"
desc = ""
tags = ["bg"]
links = [{ name = "weblate", url = "https://translate.codeberg.org/projects/forgejo/-/bg/#history" }]
other = "7 gl le iz"

[[project]]
name = "Lemmy"
desc = ""
tags = ["bg"]
links = [{ name = "weblate", url = "https://weblate.join-lemmy.org/languages/bg/lemmy/#history" }]
other = "7 gl le iz"

[[project]]
name = "Thumb-Key"
desc = ""
tags = ["bg"]
links = [{ name = "weblate", url = "https://hosted.weblate.org/projects/thumb-key/-/bg/#history" }]
other = "7 gl le iz"

[[project]]
name = "Photon"
desc = ""
tags = ["bg"]
links = [{ name = "weblate", url = "https://weblate.xylight.dev/projects/photon/-/bg/#history" }]
other = "7 gl le iz"

[[project]]
name = "Mbin"
desc = ""
tags = ["bg"]
links = [{ name = "weblate", url = "https://hosted.weblate.org/projects/mbin/-/bg/#history" }]
other = "6 gl le ne"

[[project]]
name = "TOKIMEKI"
desc = ""
tags = ["bg"]
links = [{ name = "github", url = "https://github.com/spuithori/tokimekibluesky/commits/master/src/lib/i18n/locales/bg.json" }]
other = "5 gl tr iz"

[[project]]
name = "Jerboa"
desc = ""
tags = ["bg"]
links = [{ name = "github", url = "https://github.com/dessalines/jerboa/commits/main/app/src/main/res/values-bg" }]
other = "5 gl tr iz"

[[project]]
name = "giscus"
desc = ""
tags = ["bg"]
links = [{ name = "github", url = "https://github.com/giscus/giscus/commits/main/locales/bg" }]
other = "5 gl tr iz"

[[project]]
name = "SDDM"
desc = ""
tags = ["bg"]
links = [{ name = "github", url = "https://github.com/sddm/sddm/commits/develop/data/translations/bg.ts" }]
other = "5 gl tr iz"

[[project]]
name = "LibreTranslate"
desc = ""
tags = ["bg"]
links = [{ name = "weblate", url = "https://hosted.weblate.org/projects/libretranslate/-/bg/#history" }]
other = "6 gl le ne"

[[project]]
name = "Element X"
desc = ""
tags = ["bg"]
links = [{ name = "localazy", url = "https://localazy.com/p/element" }]
other = "5 gl tr iz"

[[project]]
name = "Element Web"
desc = ""
tags = ["bg"]
links = [{ name = "localazy", url = "https://localazy.com/p/element-web" }]
other = "5 gl tr iz"

[[project]]
name = "minimal-mistakes"
desc = ""
tags = ["bg"]
links = [{ name = "github", url = "https://github.com/mmistakes/minimal-mistakes/commits/master/_data/ui-text.yml" }]
other = "4 gl tr ne"

[[project]]
name = "KeepassDX"
desc = ""
tags = ["bg"]
links = [{ name = "weblate", url = "https://hosted.weblate.org/projects/keepass-dx/-/bg/#history" }]
other = "3 ng le iz"

[[project]]
name = "Tusky"
desc = ""
tags = ["bg"]
links = [{ name = "weblate", url = "https://weblate.tusky.app/projects/tusky/tusky/bg/#history" }]
other = "2 ng le ne"

[[project]]
name = "Fedilab"
desc = ""
tags = ["bg"]
links = [{ name = "weblate", url = "https://hosted.weblate.org/projects/fedilab/-/bg/#history" }]
other = "2 ng le ne"

[[project]]
name = "Fossify"
desc = ""
tags = ["bg"]
links = [{ name = "weblate", url = "https://hosted.weblate.org/projects/fossify/-/bg/#history" }]
other = "2 ng le ne"

[[project]]
name = "Iceshrimp"
desc = ""
tags = ["bg", "stopped"]
links = [{ name = "weblate", url = "https://translate.iceshrimp.dev/languages/bg/iceshrimp/#history" }]
other = "2 ng le ne"

[[project]]
name = "Firefish"
desc = ""
tags = ["bg", "stopped"]
links = [{ name = "weblate", url = "https://hosted.weblate.org/projects/firefish/-/bg/#history" }]
other = "2 ng le ne"

[[project]]
name = "Kaiteki"
desc = ""
tags = ["bg", "stopped"]
links = [{ name = "weblate", url = "https://hosted.weblate.org/projects/kaiteki/-/bg/#history" }]
other = "2 ng le ne"

[[project]]
name = "Mangane"
desc = ""
tags = ["bg"]
links = [{ name = "github", url = "https://github.com/BDX-town/Mangane/commits/master/app/soapbox/locales/bg.json" }]
other = "1 ng tr iz"

[[project]]
name = "PinkSea"
desc = ""
tags = ["bg"]
links = [{ name = "github", url = "https://github.com/shinolabs/PinkSea/commits/master/PinkSea.Frontend/src/intl/translations/bg.json" }]
other = "0 ng tr ne"
